# Kili Engine 2
# Config file for the engine
# .ini parser version 1.0

[Window]
name = "KiliEngine" 
# Quotes are not needed

fullscreen = false
borderless = false
resizable = true
always_on_top = false

# Number of samples for msaa antialiasing set it to 0 to deactivate
# Max 16 and prefer power of two
msaa = 4

# Window size if windowed
width = 800 
height = 800

vsync = false

[EventSystem]
logging = false

# They are a lot especially the mouse so i don't log them when i don't need
logging_keyboard_events = false
logging_mouse_events = false

[Console]
# Filters trough logging levels to hide some of them
logging_info = true
logging_debug = true
logging_loading = true
logging_warning = true
logging_error = true

[Time]
# Fps limit, 0 -> unlimited, only work with vsync false
# Use integer
fps_max = 200

max_delta_time = 1.0

logging = true
log_interval = 1.0